### PR TITLE
Feature/frontend cfg

### PR DESCRIPTION
**Pull request by joshrmcdaniel**
- signal handling
- webgui improvments
- docs

### CODE REVIEW

**Comment by Black-Steel** [comment]
I try to compile this project myself,but when I try to run privaxy with "./privaxy" command, 127.0.0.1:8200 interface is not displayed

**Comment by joshrmcdaniel** [comment]
@Black-Steel i want to say off the top of my head the env var for ip is PRIVAXY_IP_ADDRESS

The config for privaxy is created under/etc/privaxy


I haven't had time to work on this. I've been using the feature/cache branch without issue for a while

**Comment by Black-Steel** [comment]
Thanks for reply.When I run privacy, the terminal displays area 1, but when I open the browser it does not display area 3. However, a prompt message such as Area 2 appears on the terminal. This problem has troubled me for a long time and has not been solved. Please help me!
privaxy-running

**Comment by joshrmcdaniel** [comment]
@Black-Steel when compiling are you compiling web_frontend prior?

**Comment by Black-Steel** [comment]
Yes, I ran the compilation command "cargo build --release -j1" directly in the privaxy root directory. I also tried running the above command in the web_frontend directory, but the same error occurred when running privaxy. I wonder if it is my rustup version ( Current version 1.27.1)

**Comment by joshrmcdaniel** [comment]
I use the following command: `cd web_frontend && npm i && trunk build; cd .. && cargo build`

Make sure you have trunk installed

**Comment by joshrmcdaniel** [comment]
Alternatively there's releases here: https://github.com/joshrmcdaniel/privaxy/actions/runs/9823442674

**Comment by Black-Steel** [comment]
Thank you, I'll try it again!

**Comment by Black-Steel** [comment]
I'm so excited, it has been successfully compiled and run. Thank you so much! !

**Comment by Black-Steel** [comment]
The filtering rules I customized under adblock v0.6.0 are invalid under adblock v0.8.x. How can I return to the software version in the Barre warehouse? Thanks!

**Pull request merged**
